### ISSUE TITLE
Ability to control the granularity of the pull request activity

### ISSUE THREAD

**Issue by bipingm** [pragbits/stash2slack#10]
Is it possible to control getting a Slack message only when a pull request is created and approved/declined and not for every code comment? The comments create a lot of noise in the channel.

**Comment by pragbits** [comment]
Scheduling this for 1.4

**Comment by pragbits** [comment]
implemented in 1.4. NOTE: Existing instances will have ALL pull request events disabled when you upgrade, unless you enable some or all events again in the repo settings config page. This is because existing instances don't currently have the filter checkboxes prior 1.4, so all events will be ignored unless you go to the config and set them.

**Comment by bipingm** [comment]
Thank you!

**Comment by mathieumg** [comment]
Tell me if you want me to open a new issue for this, but would it be possible to have this as a global setting that can be overridden, just like for the webhook URL and the channel list?

We have a lot of repositories and configuring every single one individually is tedious, and we only want the same type of notifications for all of them, which used to be the default behavior. Thanks!

**Comment by pragbits** [comment]
please open a new issue for this

**Comment by pragbits** [comment]
please open a new issue for this and I will check it when I can implement it. Thanks!

**Comment by mathieumg** [comment]
Sure! Done: https://github.com/pragbits/stash2slack/issues/15

Thank you very much! :grin:
